stages:
  - test
  - build
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

.install_task_core: &install_task_core
  before_script:
    - mvn install:install-file
        -Dfile=libs/task-core-0.3.0.jar
        -DpomFile=libs/task-core-0.3.0.pom
        -Dmaven.repo.local=.m2/repository

test:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  <<: *install_task_core
  script:
    - mvn test -Dmaven.repo.local=.m2/repository
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository

build:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  <<: *install_task_core
  script:
    - mvn clean package -DskipTests -Dmaven.repo.local=.m2/repository
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 hour
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .m2/repository

docker:
  stage: docker
  image: docker:24.0
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_API_IMAGE: $DOCKER_USERNAME/task-api
    DOCKER_DB_IMAGE: $DOCKER_USERNAME/task-db
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    # Build & Push API
    - docker build -t $DOCKER_API_IMAGE:latest .
    - docker push $DOCKER_API_IMAGE:latest
    # Build & Push DB
    - docker build -t $DOCKER_DB_IMAGE:latest ./db
    - docker push $DOCKER_DB_IMAGE:latest
  only:
    - develop
