# ── ConfigMap task-api ────────────────────────────────────────
apiVersion: v1
kind: ConfigMap
metadata:
  name: task-api-config
  namespace: devops-l3gl
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/taskdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_APPLICATION_NAME: "task-api"
  LOKI_URL: "http://host.docker.internal:3100"

---
# ── Deployment task-api ───────────────────────────────────────
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-api
  namespace: devops-l3gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-api
  template:
    metadata:
      labels:
        app: task-api
    spec:
      containers:
        - name: task-api
          image: exhorte/task-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
          # ── Variables depuis ConfigMap ──
          envFrom:
            - configMapRef:
                name: task-api-config
          # ── Mot de passe depuis Secret ──
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          # ── Limites de ressources (obligatoires) ──
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "800m"
              memory: "1Gi"
          # ── Probes Actuator ──
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8085
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8085
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 4

---
# ── Service ClusterIP task-api ────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: task-api-service
  namespace: devops-l3gl
spec:
  selector:
    app: task-api
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP

---
# ── Ingress HTTP ──────────────────────────────────────────────
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: task-api-ingress
  namespace: devops-l3gl
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /l3gl(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: task-api-service
                port:
                  number: 8085